/********************************************************************
* G__CalifaGo4.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__CalifaGo4.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__CalifaGo4();
extern void G__cpp_setup_inheritanceG__CalifaGo4();
extern void G__cpp_setup_typetableG__CalifaGo4();
extern void G__cpp_setup_memvarG__CalifaGo4();
extern void G__cpp_setup_globalG__CalifaGo4();
extern void G__cpp_setup_memfuncG__CalifaGo4();
extern void G__cpp_setup_funcG__CalifaGo4();
extern void G__set_cpp_environmentG__CalifaGo4();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "CalifaParam.h"
#include "WrapperProc.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__CalifaGo4LN_TClass;
extern G__linked_taginfo G__G__CalifaGo4LN_TBuffer;
extern G__linked_taginfo G__G__CalifaGo4LN_TMemberInspector;
extern G__linked_taginfo G__G__CalifaGo4LN_TObject;
extern G__linked_taginfo G__G__CalifaGo4LN_TNamed;
extern G__linked_taginfo G__G__CalifaGo4LN_TString;
extern G__linked_taginfo G__G__CalifaGo4LN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__CalifaGo4LN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__CalifaGo4LN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__CalifaGo4LN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__CalifaGo4LN_TGo4Parameter;
extern G__linked_taginfo G__G__CalifaGo4LN_CalifaParam;
extern G__linked_taginfo G__G__CalifaGo4LN_TGo4EventSource;
extern G__linked_taginfo G__G__CalifaGo4LN_TGo4EventElement;
extern G__linked_taginfo G__G__CalifaGo4LN_TGo4EventProcessor;
extern G__linked_taginfo G__G__CalifaGo4LN_WrapperProc;

/* STUB derived class for protected member access */
